### ISSUE TITLE
libffi-bce22613.so.6.0.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by tuler** [Prasengupta/weasyprint_for_awslambda#1]
I tried your method, but had the following error:

`libffi-bce22613.so.6.0.4: cannot open shared object file: No such file or directory`

**Comment by Prasengupta** [comment]
Can you please raise an issue in github please will be answering there

**Comment by Prasengupta** [comment]
Let me know what libraries are included in zip?

I assume you are using pycrypto if so please follow the below link I think it may help you

https://stackoverflow.com/questions/38963857/import-error-from-cyptography-hazmat-bindings-constant-time-import-lib

**Comment by Prasengupta** [comment]
@tuler  And this library doesn't work in windows operating system. Please test directly uploading into the lambda
