### ISSUE TITLE
How to deploy ?

### ISSUE THREAD

**Issue by Brachamul** [Prasengupta/weasyprint_for_awslambda#2]
Hello @Prasengupta,
Would you make it clearer for me how you actually deploy this ?

> Step 1: Download the zip file from this repository.
> Step 2: Include your main handler file in the folder and zip it, upload the zip folder to aws lambda.

What do you mean by "main handler file"? Where exactly in AWS Lambda should we upload your zip?

**Comment by willTulcoLabs** [comment]
The "main handler file" is the entry point for the lambda function i.e. the file that contains the function definition lambda will be calling.  The contents of this repo should be in the same location as the handler file.  Then you can bundle your application and deploy to lambda

**Comment by Prasengupta** [comment]
@Brachamul 
Sorry for the delay
 @willTulcoLabs Thanks for the answer

@Brachamul  yes the main handler is a file where you declare to the lambda, saying that this is the file to invoke first whenever you call the lambda.

Please follow the link for information about the lambda handler
Link:[]( https://docs.aws.amazon.com/lambda/latest/dg/python-programming-model-handler-types.html
)
